// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/lehoangvuvt/go-ent-boilerplate/internal/bootstrap"
	"github.com/lehoangvuvt/go-ent-boilerplate/internal/bootstrap/stack"
	"github.com/lehoangvuvt/go-ent-boilerplate/internal/config"
)

// Injectors from wire.go:

func InitializeContainer(ctx context.Context, cfg *config.Config) (*Container, error) {
	client, err := provideEntDB(ctx, cfg)
	if err != nil {
		return nil, err
	}
	entClient := provideEntClient(client)
	userRepository := provideUserRepository(entClient)
	transactionRepository := provideTransactionRepository(entClient)
	repositories := bootstrap.Repositories{
		UserRepository:        userRepository,
		TransactionRepository: transactionRepository,
	}
	duration := provideJWTDuration(cfg)
	jwtService := provideJWTService(cfg, duration)
	options := provideRedisOptions(cfg)
	cache, err := provideCache(ctx, options)
	if err != nil {
		return nil, err
	}
	mailService := provideResendMailService(cfg)
	rabbitMQQueue, err := provideQueueAdapter(cfg)
	if err != nil {
		return nil, err
	}
	queueProducer := provideQueueProducer(rabbitMQQueue)
	queueConsumer := provideQueueConsumer(rabbitMQQueue)
	queueCloser := provideQueueCloser(rabbitMQQueue)
	services := bootstrap.Services{
		JWTService:    jwtService,
		JWTDuration:   duration,
		CacheService:  cache,
		MailService:   mailService,
		QueueProducer: queueProducer,
		QueueConsumer: queueConsumer,
		QueueCloser:   queueCloser,
	}
	idempotencyStore := provideIdempotencyStore(cfg)
	stores := bootstrap.Stores{
		IdempotencyStore: idempotencyStore,
	}
	handlerBootstrapArgs := provideHandlerArgs(repositories, services, stores)
	mux := bootstrap.BootstrapHandler(handlerBootstrapArgs)
	container := &Container{
		Router: mux,
		DB:     client,
	}
	return container, nil
}

func InitializeWorker(ctx context.Context, cfg *config.Config) (bootstrapstack.WorkerRunner, func(), error) {
	rabbitMQQueue, err := provideQueueAdapter(cfg)
	if err != nil {
		return nil, nil, err
	}
	queueConsumer := provideQueueConsumer(rabbitMQQueue)
	queueCloser := provideQueueCloser(rabbitMQQueue)
	mailService := provideResendMailService(cfg)
	queueHandler := provideRegisterEmailHandler(mailService)
	workerRunner := provideWorkerRunner(queueConsumer, queueCloser, queueHandler)
	return workerRunner, func() {
	}, nil
}
