// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/google/wire"
	"github.com/lehoangvuvt/go-ent-boilerplate/internal/bootstrap"
	"github.com/lehoangvuvt/go-ent-boilerplate/internal/config"
)

// Injectors from wire.go:

func InitializeContainer(ctx context.Context, cfg *config.Config) (*Container, error) {
	client, err := provideEntDB(ctx, cfg)
	if err != nil {
		return nil, err
	}
	entClient := provideEntClient(client)
	userRepository := provideUserRepository(entClient)
	transactionRepository := provideTransactionRepository(entClient)
	repositories := bootstrap.Repositories{
		UserRepository:        userRepository,
		TransactionRepository: transactionRepository,
	}
	duration := provideJWTDuration(cfg)
	jwtService := provideJWTService(cfg, duration)
	options := provideRedisOptions(cfg)
	cache, err := provideCache(ctx, options)
	if err != nil {
		return nil, err
	}
	services := bootstrap.Services{
		JWTService:   jwtService,
		JWTDuration:  duration,
		CacheService: cache,
	}
	idempotencyStore := provideIdempotencyStore(cfg)
	stores := bootstrap.Stores{
		IdempotencyStore: idempotencyStore,
	}
	handlerBootstrapArgs := provideHandlerArgs(repositories, services, stores)
	mux := bootstrap.BootstrapHandler(handlerBootstrapArgs)
	container := &Container{
		Router: mux,
		DB:     client,
	}
	return container, nil
}

// wire.go:

var containerSet = wire.NewSet(
	provideEntDB,
	provideEntClient,
	provideUserRepository,
	provideTransactionRepository,
	provideJWTDuration,
	provideJWTService,
	provideRedisOptions,
	provideCache,
	provideIdempotencyStore,
	provideHandlerArgs, wire.Struct(new(bootstrap.Repositories), "*"), wire.Struct(new(bootstrap.Services), "*"), wire.Struct(new(bootstrap.Stores), "*"), wire.Struct(new(Container), "*"), bootstrap.BootstrapHandler,
)
