// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lehoangvuvt/go-ent-boilerplate/ent/predicate"
	"github.com/lehoangvuvt/go-ent-boilerplate/ent/transaction"
	"github.com/lehoangvuvt/go-ent-boilerplate/ent/user"
	transactionmethoddomain "github.com/lehoangvuvt/go-ent-boilerplate/internal/domain/transaction/method"
)

// TransactionUpdate is the builder for updating Transaction entities.
type TransactionUpdate struct {
	config
	hooks    []Hook
	mutation *TransactionMutation
}

// Where appends a list predicates to the TransactionUpdate builder.
func (_u *TransactionUpdate) Where(ps ...predicate.Transaction) *TransactionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TransactionUpdate) SetAmount(v int64) *TransactionUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableAmount(v *int64) *TransactionUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TransactionUpdate) AddAmount(v int64) *TransactionUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *TransactionUpdate) SetCurrency(v string) *TransactionUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableCurrency(v *string) *TransactionUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TransactionUpdate) SetUserID(v uuid.UUID) *TransactionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableUserID(v *uuid.UUID) *TransactionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TransactionUpdate) SetStatus(v transaction.Status) *TransactionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableStatus(v *transaction.Status) *TransactionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *TransactionUpdate) SetMethod(v transaction.Method) *TransactionUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableMethod(v *transaction.Method) *TransactionUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetVisaDetails sets the "visa_details" field.
func (_u *TransactionUpdate) SetVisaDetails(v *transactionmethoddomain.VisaDetails) *TransactionUpdate {
	_u.mutation.SetVisaDetails(v)
	return _u
}

// ClearVisaDetails clears the value of the "visa_details" field.
func (_u *TransactionUpdate) ClearVisaDetails() *TransactionUpdate {
	_u.mutation.ClearVisaDetails()
	return _u
}

// SetBankingDetails sets the "banking_details" field.
func (_u *TransactionUpdate) SetBankingDetails(v *transactionmethoddomain.BankingDetails) *TransactionUpdate {
	_u.mutation.SetBankingDetails(v)
	return _u
}

// ClearBankingDetails clears the value of the "banking_details" field.
func (_u *TransactionUpdate) ClearBankingDetails() *TransactionUpdate {
	_u.mutation.ClearBankingDetails()
	return _u
}

// SetEwalletDetails sets the "ewallet_details" field.
func (_u *TransactionUpdate) SetEwalletDetails(v *transactionmethoddomain.EWalletDetails) *TransactionUpdate {
	_u.mutation.SetEwalletDetails(v)
	return _u
}

// ClearEwalletDetails clears the value of the "ewallet_details" field.
func (_u *TransactionUpdate) ClearEwalletDetails() *TransactionUpdate {
	_u.mutation.ClearEwalletDetails()
	return _u
}

// SetQrDetails sets the "qr_details" field.
func (_u *TransactionUpdate) SetQrDetails(v *transactionmethoddomain.QRDetails) *TransactionUpdate {
	_u.mutation.SetQrDetails(v)
	return _u
}

// ClearQrDetails clears the value of the "qr_details" field.
func (_u *TransactionUpdate) ClearQrDetails() *TransactionUpdate {
	_u.mutation.ClearQrDetails()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TransactionUpdate) SetCreatedAt(v time.Time) *TransactionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableCreatedAt(v *time.Time) *TransactionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TransactionUpdate) SetUpdatedAt(v time.Time) *TransactionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TransactionUpdate) SetUser(v *User) *TransactionUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TransactionMutation object of the builder.
func (_u *TransactionUpdate) Mutation() *TransactionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TransactionUpdate) ClearUser() *TransactionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TransactionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TransactionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TransactionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := transaction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransactionUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := transaction.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Transaction.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := transaction.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Transaction.method": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Transaction.user"`)
	}
	return nil
}

func (_u *TransactionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(transaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(transaction.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(transaction.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(transaction.FieldMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.VisaDetails(); ok {
		_spec.SetField(transaction.FieldVisaDetails, field.TypeJSON, value)
	}
	if _u.mutation.VisaDetailsCleared() {
		_spec.ClearField(transaction.FieldVisaDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.BankingDetails(); ok {
		_spec.SetField(transaction.FieldBankingDetails, field.TypeJSON, value)
	}
	if _u.mutation.BankingDetailsCleared() {
		_spec.ClearField(transaction.FieldBankingDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.EwalletDetails(); ok {
		_spec.SetField(transaction.FieldEwalletDetails, field.TypeJSON, value)
	}
	if _u.mutation.EwalletDetailsCleared() {
		_spec.ClearField(transaction.FieldEwalletDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.QrDetails(); ok {
		_spec.SetField(transaction.FieldQrDetails, field.TypeJSON, value)
	}
	if _u.mutation.QrDetailsCleared() {
		_spec.ClearField(transaction.FieldQrDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(transaction.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(transaction.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.UserTable,
			Columns: []string{transaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.UserTable,
			Columns: []string{transaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TransactionUpdateOne is the builder for updating a single Transaction entity.
type TransactionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransactionMutation
}

// SetAmount sets the "amount" field.
func (_u *TransactionUpdateOne) SetAmount(v int64) *TransactionUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableAmount(v *int64) *TransactionUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TransactionUpdateOne) AddAmount(v int64) *TransactionUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *TransactionUpdateOne) SetCurrency(v string) *TransactionUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableCurrency(v *string) *TransactionUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TransactionUpdateOne) SetUserID(v uuid.UUID) *TransactionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableUserID(v *uuid.UUID) *TransactionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TransactionUpdateOne) SetStatus(v transaction.Status) *TransactionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableStatus(v *transaction.Status) *TransactionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *TransactionUpdateOne) SetMethod(v transaction.Method) *TransactionUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableMethod(v *transaction.Method) *TransactionUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetVisaDetails sets the "visa_details" field.
func (_u *TransactionUpdateOne) SetVisaDetails(v *transactionmethoddomain.VisaDetails) *TransactionUpdateOne {
	_u.mutation.SetVisaDetails(v)
	return _u
}

// ClearVisaDetails clears the value of the "visa_details" field.
func (_u *TransactionUpdateOne) ClearVisaDetails() *TransactionUpdateOne {
	_u.mutation.ClearVisaDetails()
	return _u
}

// SetBankingDetails sets the "banking_details" field.
func (_u *TransactionUpdateOne) SetBankingDetails(v *transactionmethoddomain.BankingDetails) *TransactionUpdateOne {
	_u.mutation.SetBankingDetails(v)
	return _u
}

// ClearBankingDetails clears the value of the "banking_details" field.
func (_u *TransactionUpdateOne) ClearBankingDetails() *TransactionUpdateOne {
	_u.mutation.ClearBankingDetails()
	return _u
}

// SetEwalletDetails sets the "ewallet_details" field.
func (_u *TransactionUpdateOne) SetEwalletDetails(v *transactionmethoddomain.EWalletDetails) *TransactionUpdateOne {
	_u.mutation.SetEwalletDetails(v)
	return _u
}

// ClearEwalletDetails clears the value of the "ewallet_details" field.
func (_u *TransactionUpdateOne) ClearEwalletDetails() *TransactionUpdateOne {
	_u.mutation.ClearEwalletDetails()
	return _u
}

// SetQrDetails sets the "qr_details" field.
func (_u *TransactionUpdateOne) SetQrDetails(v *transactionmethoddomain.QRDetails) *TransactionUpdateOne {
	_u.mutation.SetQrDetails(v)
	return _u
}

// ClearQrDetails clears the value of the "qr_details" field.
func (_u *TransactionUpdateOne) ClearQrDetails() *TransactionUpdateOne {
	_u.mutation.ClearQrDetails()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TransactionUpdateOne) SetCreatedAt(v time.Time) *TransactionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableCreatedAt(v *time.Time) *TransactionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TransactionUpdateOne) SetUpdatedAt(v time.Time) *TransactionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TransactionUpdateOne) SetUser(v *User) *TransactionUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TransactionMutation object of the builder.
func (_u *TransactionUpdateOne) Mutation() *TransactionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TransactionUpdateOne) ClearUser() *TransactionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the TransactionUpdate builder.
func (_u *TransactionUpdateOne) Where(ps ...predicate.Transaction) *TransactionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TransactionUpdateOne) Select(field string, fields ...string) *TransactionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Transaction entity.
func (_u *TransactionUpdateOne) Save(ctx context.Context) (*Transaction, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionUpdateOne) SaveX(ctx context.Context) *Transaction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TransactionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := transaction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransactionUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := transaction.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Transaction.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := transaction.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Transaction.method": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Transaction.user"`)
	}
	return nil
}

func (_u *TransactionUpdateOne) sqlSave(ctx context.Context) (_node *Transaction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Transaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transaction.FieldID)
		for _, f := range fields {
			if !transaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(transaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(transaction.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(transaction.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(transaction.FieldMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.VisaDetails(); ok {
		_spec.SetField(transaction.FieldVisaDetails, field.TypeJSON, value)
	}
	if _u.mutation.VisaDetailsCleared() {
		_spec.ClearField(transaction.FieldVisaDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.BankingDetails(); ok {
		_spec.SetField(transaction.FieldBankingDetails, field.TypeJSON, value)
	}
	if _u.mutation.BankingDetailsCleared() {
		_spec.ClearField(transaction.FieldBankingDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.EwalletDetails(); ok {
		_spec.SetField(transaction.FieldEwalletDetails, field.TypeJSON, value)
	}
	if _u.mutation.EwalletDetailsCleared() {
		_spec.ClearField(transaction.FieldEwalletDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.QrDetails(); ok {
		_spec.SetField(transaction.FieldQrDetails, field.TypeJSON, value)
	}
	if _u.mutation.QrDetailsCleared() {
		_spec.ClearField(transaction.FieldQrDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(transaction.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(transaction.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.UserTable,
			Columns: []string{transaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.UserTable,
			Columns: []string{transaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Transaction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
